version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword
    ports:
      - "1433:1433"

  app:
    build: .
    container_name: dotnet-docker-app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=YourDatabaseName;User=sa;Password=YourStrongPassword;
    ports:
      - "5000:5000"
    depends_on:
      - db
